import { ShieldFilterList } from '../shared/types';

/**
 * Standard reputable filter lists supported by NEXUS Shield
 */
export const DEFAULT_FILTER_LISTS: ShieldFilterList[] = [
  {
    id: 'easylist',
    name: 'EasyList',
    description: 'Primary ad-blocking filter list targeting banners, overlays, video ads, and sponsored content.',
    url: 'https://easylist.to/easylist/easylist.txt',
    enabled: true,
    ruleCount: 1420,
    lastUpdated: Date.now() - 3600 * 24 * 1000,
    format: 'adblock',
  },
  {
    id: 'easyprivacy',
    name: 'EasyPrivacy',
    description: 'Privacy protection list blocking behavioral telemetry, cross-site trackers, scripts, and fingerprinting.',
    url: 'https://easylist.to/easylist/easyprivacy.txt',
    enabled: true,
    ruleCount: 980,
    lastUpdated: Date.now() - 3600 * 24 * 1000,
    format: 'adblock',
  },
  {
    id: 'peter-lowe',
    name: "Peter Lowe's Ad & Tracker Server List",
    description: 'Curated list of known adservers, survey popups, and profiling beacons.',
    url: 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext',
    enabled: true,
    ruleCount: 840,
    lastUpdated: Date.now() - 3600 * 24 * 1000,
    format: 'hosts',
  },
  {
    id: 'nexus-phishing-shield',
    name: 'NEXUS Phishing & Malware Protection Feed',
    description: 'Heuristic and signature database blocking deceptive domains, credential harvesters, and tech support scams.',
    url: 'https://urlhaus.abuse.ch/downloads/hostfile/',
    enabled: true,
    ruleCount: 650,
    lastUpdated: Date.now() - 3600 * 24 * 1000,
    format: 'hosts',
  },
];

/**
 * Bundled offline advertising hostnames (EasyList core subset)
 */
export const BUNDLED_AD_DOMAINS: string[] = [
  'doubleclick.net',
  'googlesyndication.com',
  'googleadservices.com',
  'adnxs.com',
  'rubiconproject.com',
  'taboola.com',
  'outbrain.com',
  'adroll.com',
  'criteo.com',
  'criteo.net',
  'pubmatic.com',
  'openx.net',
  'amazon-adsystem.com',
  'casale-media.com',
  'advertising.com',
  'adcolony.com',
  'inmobi.com',
  'popads.net',
  'propellerads.com',
  'bidswitch.net',
  'revcontent.com',
  'mgid.com',
  'adservice.google.com',
  'pagead2.googlesyndication.com',
  'smartadserver.com',
  'yieldmo.com',
  'zemanta.com',
  'adform.net',
  'adtechus.com',
  'adblade.com',
  'adzerk.net',
  'ad-delivery.net',
  'adscale.de',
  'exponential.com',
  'media.net',
  'tribalfusion.com',
  'trafficfactory.biz',
  'zergnet.com',
  'buysellads.com',
  'adpushup.com',
  'carbonads.net',
  'carbonads.com',
  'adthrive.com',
  'mediavine.com',
  'infolinks.com',
  'sovrn.com',
  'lijit.com',
  'contextweb.com',
  'chitika.com',
  'adspirit.de',
  'adserver.com',
  'serving-sys.com',
  'adbutler.com',
  'moatads.com',
  'adfox.ru',
  'yandexadexchange.net',
  'aniview.com',
  'teads.tv',
  'spotxchange.com',
  'spotx.tv',
  'springserve.com',
  'admanmedia.com',
  'unruly.co',
];

/**
 * Bundled offline tracking & telemetry hostnames (EasyPrivacy core subset)
 */
export const BUNDLED_TRACKER_DOMAINS: string[] = [
  'google-analytics.com',
  'googletagmanager.com',
  'connect.facebook.net',
  'facebook.com/tr',
  'analytics.twitter.com',
  'hotjar.com',
  'hotjar.io',
  'mixpanel.com',
  'scorecardresearch.com',
  'segment.io',
  'segment.com',
  'clarity.ms',
  'quantserve.com',
  'newrelic.com',
  'branch.io',
  'amplitude.com',
  'mouseflow.com',
  'fullstory.com',
  'crazyegg.com',
  'chartbeat.com',
  'optimizely.com',
  'kissmetrics.com',
  'statcounter.com',
  'luckyorange.com',
  'heapanalytics.com',
  'loggly.com',
  'datadoghq-browser-agent.com',
  'sentry.io/api',
  'bugsnag.com',
  'appsflyer.com',
  'adjust.com',
  'kochava.com',
  'telemetry.mozilla.org',
  'metrics.icloud.com',
  'matomo.org',
  'piwik.pro',
  'woopra.com',
  'inspectlet.com',
  'clicky.com',
  'statcounter.com',
  'qualaroo.com',
  'appcues.com',
  'pendo.io',
  'permutive.com',
  'bombora.com',
  'rlcdn.com',
  'demdex.net',
  'bluekai.com',
  'krxd.net',
  'agkn.com',
  'exelator.com',
  'tapad.com',
  'bkrtx.com',
  'scorecardresearch.com',
  'everesttech.net',
];

/**
 * Bundled unwanted pop-up, pop-under, and deceptive redirector networks
 */
export const BUNDLED_POPUP_DOMAINS: string[] = [
  'popads.net',
  'popcash.net',
  'propellerads.com',
  'exoclick.com',
  'adsterra.com',
  'yllix.com',
  'clickadu.com',
  'trafficjunky.com',
  'adcash.com',
  'hilltopads.com',
  'ad-maven.com',
  'richads.com',
  'monetag.com',
  'evadav.com',
  'galaksion.com',
  'popup-ad-network.com',
  'onclickads.net',
  'pushame.com',
  'directrev.com',
  'popmyads.com',
  'revenuehits.com',
  'bidvertiser.com',
];

/**
 * Bundled phishing, scam, and malware test/known signatures
 */
export const BUNDLED_MALICIOUS_DOMAINS: string[] = [
  'phishing-bank-login.com',
  'malware-test.com',
  'crypto-drainer.xyz',
  'phishing-bank-login-secure.com',
  'update-browser-critical-patch.net',
  'win-security-alert-warning09.com',
  'apple-security-verify-id.net',
  'paypal-verification-center.info',
  'crypto-airdrop-claim-now.xyz',
  'metamask-wallet-auth-sync.co',
  'microsoft-support-alert-fix.net',
  'urgent-account-suspended-verify.com',
  'malware-test-destination.nexus',
  'phishing-test-destination.nexus',
  'scam-alert-test.nexus',
  'drive-by-download-test.nexus',
  'test-phishing-threat.com',
  'test-malware-payload.com',
  'ransomware-warning-tech-support.com',
  'free-giftcard-survey-winner.xyz',
  'urgent-security-checkup-required.info',
];

/**
 * Ad path pattern heuristics
 */
export const BUNDLED_AD_PATTERNS: string[] = [
  '/ads/',
  '/adserver/',
  '/ad-banner/',
  '/pagead/imgad',
  '/pagead/ads',
  '/adservice/',
  '&ad_type=',
  '?ad_client=',
  '/ad_iframe',
  '/sponsored-post-ad/',
  '/telemetry/ads/',
  '/bannerads/',
  '/sponsored_banner',
  '/googleads.js',
  '/adclick.',
  '/adserver.',
  '/adsystem.',
  '/popunder.',
];
